### ISSUE TITLE
for insert to er sub-table，if  exists searching conn to parent-table‘s killed, expect insert fail

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1430] opened 2019-10-12 05:58 UTC
* **dble version：**  
5.6.29-dble-9.9.9.9-d4ca2abf59b5c20c910d77078e7f3d068797a892-20191011083537

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
```
    <schema name="schema1" sqlMaxLimit="100">
        <table dataNode="dn1,dn2" name="sharding_2_t1" rule="hash-two" />
        <table name="table_b" dataNode="dn1,dn2" rule="hash-two">
        <childTable name="table_c" joinKey="name" parentKey="name">
        </childTable>
        </table>
    </schema>
    <dataNode dataHost="172.100.9.6" database="db1" name="dn1" />
    <dataNode dataHost="172.100.9.5" database="db2" name="dn2" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  prepare er tables in dble
```mysql
drop table if exists table_b;

drop table if exists table_c;

create table table_b(id int,name varchar(40));

create table table_c(name varchar(40),id int);

insert into table_b set id = 1,name = "xx"
```

  step2.lock tables in dn1,dn2 for response delay
in both dn1,dn2 backend mysql server execute:
```mysql
lock tables table_b write
```
mark the sessions as session1, session2
step3. in dble query:
```mysql
insert into table_c set id = 5,name = "xx";
```
step4. kill backend conn for searching parent sharding:
on session1, execute: kill thread of {SELECT table_b.NAME FROM table_b WHERE  table_b.NAME='xx'}
then unlock tables on both session1, session2
step5. query in step3 get feedback: success, as below:
```mysql
mysql> insert into table_c set id = 5,name = "xx";
Query OK, 1 row affected (7.28 sec)

mysql> select * from table_c;
+------+------+
| name | id   |
+------+------+
| xx   |    5 |
+------+------+
1 row in set (0.01 sec)
```
* **expect result：**  
    1.step5, insert into table_c set id = 5,name = "xx"; got error, for may there duplicate record in dn1 for name='xx'
* **real result：**  
    1.the insert ignored the killed conn's resultset in step5
* **supplements：**  
    1.founded by test case in testlink: id=dble-7244

**Comment by yanhuqing666** [comment] 2019-12-12 02:49
looks like not a bug，need to discuss

**Comment by Baofengqi** [comment] 2019-12-30 09:52
I also think it's not a bug.

**Comment by wjl1619** [comment] 2020-02-12 08:24
This is not a issue, so closed it. but create a new reletative issue: https://github.com/actiontech/dble/issues/1655

**Closed by wjl1619** 2020-02-12 08:24 UTC
