### ISSUE TITLE
drop ddl hang

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1270] opened 2019-07-22 06:39 UTC
* **dble version：**  
5.6.29-dble-2.19.05.0-83bcd35b0a53c717a7fd8838ff1dcdf5fbb31353-20190702053754
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<?xml version="1.0"?>
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/">
         <schema name="mytest">
                 <table name="sbtest1" primaryKey="id" dataNode="dn$1-9" rule="hash-sysbench" />
        </schema>
        <dataNode name="dn$1-3" dataHost="host_1" database="mfdb$1-3" />
        <dataNode name="dn$4-6" dataHost="host_2" database="mfdb$4-6" />
        <dataNode name="dn$7-9" dataHost="host_3" database="mfdb$7-9" />
        <dataHost name="host_1" maxCon="900" minCon="500" balance="0" switchType="-1"  slaveThreshold="-1">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM1" url="xx.xx.xx.xx:xxxx" user="xxx" password="xxx"></writeHost>
        </dataHost>
        <dataHost name="host_2" maxCon="900" minCon="500" balance="0" switchType="-1"  slaveThreshold="-1">                                                   <heartbeat>select user()</heartbeat>
            <writeHost host="hostM2" url="xx.xx.xx.xx:xxxx" user="xxx" password="xxx"></writeHost>
        </dataHost>
        <dataHost name="host_3" maxCon="900" minCon="500" balance="0" switchType="-1" slaveThreshold="-1">
            <heartbeat>select user()</heartbeat>
            <writeHost host="hostM3" url="xx.xx.xx.xx:xxxx" user="xxx" password="xxx"></writeHost>
        </dataHost>
</dble:schema>


```

**rule.xml**  

```
<!DOCTYPE dble:rule SYSTEM "rule.dtd">
<dble:rule xmlns:dble="http://dble.cloud/">
    <tableRule name="hash-sysbench">
        <rule>
            <columns>id</columns>
                    <algorithm>mod</algorithm>
            </rule>
    </tableRule>

    <function name="mod" class="Hash">
           <property name="partitionCount">9</property>
           <property name="partitionLength">1</property>
    </function>
</dble:rule>
```

**server.xml**  

```


```

* **steps：**    
    step1. use sysbench 1.0.15 oltp_update_index.lua test for many times(>5)
 sysbench --mysql-db=mytest --mysql-host=xx.xx.xx.xx --mysql-port=xxx --mysql-user=xxx --mysql-password=xxx --auto_inc=off --tables=1 --table-size=10000000 --threads=128 --report-interval=3 --time=600 --max-requests=0 --percentile=95 --create_secondary=off /usr/local/share/sysbench/oltp_update_index.lua run
    step2. during sysbench run test, backend mysql config(mainly innodb_purge_threads) has been changed and restart mysql, also restart dble
    step3.execute sysbench cleanup with command:
sysbench --mysql-db=mytest --mysql-host=xx.xx.xx.xx --mysql-port=xxx --mysql-user=xxx --mysql-password=xxx --auto_inc=off --tables=1 --table-size=10000000 --threads=128 --report-interval=3 --time=600 --max-requests=0 --percentile=95 --create_secondary=off
/usr/local/share/sysbench/oltp_update_index.lua cleanup 
* **expect result：**  
    1. step3 execute successfully
* **real result：**  
    1. step3 hang at:
Dropping table 'sbtest1'...
* **supplements：**  
    1.jstack during hang: 
[drop_ddl_hang.jstack.log](https://github.com/actiontech/dble/files/3415996/drop_ddl_hang.jstack.log)
   2. dev @sunsun314 has confirmed there is no usefull log in dble.log (default log level: info)
    3. there is an error with the backend mysql, but whether relevant is not sure
```
2019-07-22T05:24:47.228670Z 1141 [ERROR] InnoDB: Table 
mysql`.`innodb_table_stats` not found.
```
    4.there is a table not dropped in a backend datanode, try "drop table if exists sbtest1" in that datanode, query success, also got error:
```
2019-07-22T05:24:47.228670Z 1141 [ERROR] InnoDB: Table 
mysql`.`innodb_table_stats` not found.
```

**Comment by irene-coming** [comment] 2019-07-22 07:06
with the above env:
step1:
```
mysql> kill @@ddl_lock where schema='mytest' and table='sbtest1';
Query OK, 0 rows affected (0.01 sec)
ddl lock is removed successfully!

mysql> show @@ddl;
Empty set (0.00 sec)

mysql> reload @@metadata;
Query OK, 1 row affected (0.04 sec)
reload metadata success
```
step2 :
```
mysql> show @@connection;
```
**expect result:**
after step1, sysbench cmdline finish hang, but sysbench still hang

**supplement:**
after step2, sysbench finish hang with:
Dropping table 'sbtest1'...
FATAL: mysql_drv_query() returned error 2013 (Lost connection to MySQL server during query) for query 'DROP TABLE IF EXISTS sbtest1'
FATAL: `cleanup' function failed: /usr/share/sysbench/oltp_common.lua:392: SQL error, errno = 2013, state = 'HY000': Lost connection to MySQL server during query
after kill @@ddl_lock ... success, the sysbench cmdline still hang

**Comment by Baofengqi** [comment] 2020-01-07 02:15
can‘t reproduce.

**Comment by wjl1619** [comment] 2020-02-12 03:08
Can't reproduce on dble version: 5.6.29-dble-2.19.11.0-a8b6cf2daf30fd1dedb6e91294d8b6839e730386-20200211092945, so closed it.

**Closed by wjl1619** 2020-02-12 03:08 UTC
