### ISSUE TITLE
Statement contains chinese characters `;`,  will return ok directly

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1388] opened 2019-09-10 06:08 UTC
* **dble version：**  
dble-9.9.9.9-83b87f4e37700caea0b90e77712ff354b08d694b-20190909070555
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
```
drop table test；;
```
* **expect result：**  
    1.
```
mysql> drop table test；;
ERROR 1051 (42S02): Unknown table 'schema1.test；'
```
* **real result：**  
    1.
```
mysql> drop table test；;
Query OK, 0 rows affected (0.00 sec)
```
* **supplements：**  
    1.
```
2019-09-10 06:01:42.135 DEBUG [BusinessExecutor0] (com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:321)) - ServerConnection [frontId=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest] drop table test；
2019-09-10 06:01:42.135 DEBUG [BusinessExecutor0] (com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:44)) - ServerConnection [frontId=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]drop table test；
```

**Comment by Baofengqi** [comment] 2019-09-26 10:11
The issue can't reproduce.

**Comment by wjl1619** [comment] 2019-09-29 08:08
we can reproduce by following steps:
step1.set the lang as UTF-8 by excuting "export LANG=en_US.UTF-8" on your machine
step2.excute the sql :  mysql -p111111 -utest -P8066 -h172.100.9.1 -e "drop table if exists schema1.test；;"

PS: details in dble.log as below:
2019-09-29 16:00:56.607 DEBUG [BusinessExecutor3] (com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:321)) - ServerConnection [frontId=5, schema=null, host=172.100.9.1, user=test,txIsolation=3, autocommit=true, schema=null] drop table if exists schema1.test；
2019-09-29 16:00:56.607 DEBUG [BusinessExecutor3] (com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:44)) - ServerConnection [frontId=5, schema=null, host=172.100.9.1, user=test,txIsolation=3, autocommit=true, schema=null]drop table if exists schema1.test；

**Comment by wjl1619** [comment] 2019-10-08 07:07
verified on version: 5.6.29-dble-9.9.9.9-02cef4c18ca820fe4401a62c6e6c8053f689b467-20190926091030
This issue is not a REAL issue, coz dble has the same behavior as mysql, so closed it.

**Closed by wjl1619** 2019-10-08 07:07 UTC
